# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obliscence < Formula
  desc "Archive and search Claude Code conversations"
  homepage "https://github.com/beaugunderson/obliscence"
  version "0.10.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/beaugunderson/obliscence/releases/download/v0.10.0/obliscence_0.10.0_darwin_arm64.tar.gz"
    sha256 "18ad670c6236c00b3fa384dcbd4ddf0d6aace561332bd0b8cf112e829e9bf912"

    define_method(:install) do
      bin.install "obliscence"
    end
  end

  test do
    system bin/"obliscence", "stats"
  end
end
