# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obliscence < Formula
  desc "Archive and search Claude Code conversations"
  homepage "https://github.com/beaugunderson/obliscence"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/beaugunderson/obliscence/releases/download/v0.2.0/obliscence_0.2.0_darwin_arm64.tar.gz"
    sha256 "847407bae8409c910302f560d621dc9c708642a4d4096394b1d0ba1f68b4328e"

    define_method(:install) do
      bin.install "obliscence"
    end
  end

  test do
    system bin/"obliscence", "stats"
  end
end
