# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracer" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "94975b89da42775b7e07fc6fb2d92e3aeef64bdd07ef2e49d7b62867e54ed6e7"
      url "https://github.com/beaugunderson/tracer/releases/download/v#{version}/tracer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a4b2196a09e9d74e84c80192e3b6a5d18bade05783d38b99908cdb9a1c65bfb"
      url "https://github.com/beaugunderson/tracer/releases/download/v#{version}/tracer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f253a4f6c9c1c68a85f90ff40422d549c84d1c044265e7f36eb769d29e85c58e"
      url "https://github.com/beaugunderson/tracer/releases/download/v#{version}/tracer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "50d2c80759a20bdec46dc7abce514163e0feca4ac0420e9cd5646e3839520b17"
      url "https://github.com/beaugunderson/tracer/releases/download/v#{version}/tracer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tracer"
  desc "mtr-style continuous traceroute with braille sparklines"
  homepage "https://github.com/beaugunderson/tracer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tracer"]
    end
  end

  # No zap stanza required

end
